services:
  java_app:
    container_name: java_app
    image: movies-challenge-api:1.0.0
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=Xx7nRnMJ7t1EVpG8Yw/5vA+dyKCt6I1yyou4Pjl8YI8=
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgrest_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres